spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/czmxx/spring-cloud-config
          default-label: master
          search-paths: config-profile
#          username:
#          password:

server:
  port: 8008



